server.port=9090
client.url=http://localhost:8080
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:6642/main}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:main}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:main}
spring.jpa.hibernate.ddl-auto=update